config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: { registrations: 'users/registrations' }
  get 'show_account', to: 'bank_account#show_account'
  resources :transactions
  put 'change_account_status', to: 'bank_account#change_bank_account_status'

  root 'bank_account#show_account'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/bank_account.rb
class BankAccount < ApplicationRecord
  before_create :generate_bank_account_number

  belongs_to :user
  has_many :sended, class_name: 'Transaction', foreign_key: 'account_sender_id'
  has_many :received, class_name: 'Transaction', foreign_key: 'account_receiver_id'

  validates :account_number, uniqueness: true
  validates :balance, numericality: { greater_than_or_equal_to: 0 }

  def transactions
    Transaction.where(account_sender_id: id)
               .or(Transaction.where(account_receiver_id: id))
               .distinct
               .order(created_at: :desc)
  end

  private

  def generate_bank_account_number
    number_of_digits = 5

    self.account_number = SecureRandom.random_number(10**number_of_digits)
  end
end

app/controllers/bank_account_controller.rb
class BankAccountController < ApplicationController
  include ActionView::Helpers::NumberHelper

  before_action :authenticate_user!

  def show_account
    user_id = current_user.id
    @bank_account = User.find(user_id).bank_account
    if params[:'/show_account'] && (params[:'/show_account'][:initial_date] || params[:'/show_account'][:final_date])
      @transactions = filter_by_date(params[:'/show_account'][:initial_date], params[:'/show_account'][:final_date])
    else
      @transactions = nil
    end

    @transactions_to_export = filter_by_date(params[:initial_date], params[:final_date]) if params[:initial_date] || params[:final_date]

    respond_to do |format|
      format.html
      format.csv do
        headers['Content-Disposition'] = "attachment; filename=\"transacoes_#{Time.zone.today}.csv\""
        headers['Content-Type'] ||= 'text/csv'
      end
    end
  end

  def change_bank_account_status
    user_id = current_user.id
    bank_account = User.find(user_id).bank_account
    current_status = bank_account.active?

    bank_account.update(active: !current_status)
    redirect_to show_account_path(current_user, format: :html)
  end

  private

  def filter_by_date(initial_date, final_date)
    initial_date = initial_date.blank? ? @bank_account.created_at : Time.zone.parse(initial_date)
    final_date = final_date.blank? ? Time.zone.now : Time.zone.parse(final_date) + 86_399

    @bank_account.transactions.where('created_at >= ? AND created_at <= ?', initial_date, final_date)
  end

  def transaction_params
    params.permit(:initial_date, :final_date)
  end
end

app/helpers/bank_account_helper.rb
module BankAccountHelper
end

app/views/bank_account/show.html.erb
<p>show action</p>
<div>
  <p>Saldo: <%=@bank_account.balance%></p>
  <% @bank_account.transactions.each do |transaction| %>
    <p> R$<%=transaction.amount.round(2) %> - <%=transaction.transaction_type %> </p>
  <% end %>
  <button>Fazer depósito</button>
  <button>Fazer saque</button>
  <button>Fazer transferência</button>
  <button>Exportar extrato</button>
</div>

app/views/bank_account/show_account.csv.erb
<%- headers = ['Tipo de transação', 'Valor', 'Taxa', 'Destinatário', 'Data'] -%>
<%= CSV.generate_line headers %>
<% @transactions_to_export.each do |transaction| %>
  <%= CSV.generate_line(
    [transaction.transaction_type, transaction.amount, transaction.fee, transaction.account_receiver.user.full_name, transaction.created_at]
  ) -%>
<% end %>

app/views/bank_account/show_account.html.erb
<div class='container-fluid bank-account'>
  <div class='row'>
    <div class='col-12'>
      <h1>Bem-vindo(a) <%=current_user.first_name.titleize%>!</h1>
    </div>
  </div>

  <div class='row mb-4 balance-info'>
    <div class='col-2'>
      <div class='row mt-4'>
        <div class='col-12'>
          <span>Saldo</span>
        </div>
      </div>

      <div class='row'>
        <div class='col-12'>
          <h2 class='display-6'><%=number_to_currency(@bank_account.balance, unit: 'R$', separator: ',')%></h2>
        </div>
      </div>
    </div>

    <div class='col-4'>
      <div class='row mt-4'>
        <div class='col-12'>
          <span>Conta</span>
        </div>
      </div>

      <div class='row'>
        <div class='col-12'>
          <h2 class='display-6'><%=@bank_account.account_number%></h2>
        </div>
      </div>
    </div>
  </div>

  <%if @bank_account.active%>
    <div class='row mb-4'>
      <div class='col-2'>
        <%= link_to 'Realizar transação', new_transaction_path, class: "btn button-new-transaction" %>
      </div>
      <div class='col-10'></div>
    </div>
  <%end%>

  <div class='row d-flex align-items-end'>
    <div class='col-6'>
      <span>Transações</span>
    </div>
    <%if params[:'/show_account']%>
      <div class='col-6 d-flex justify-content-end'>
        <%= link_to 'Exportar', show_account_path(initial_date: params[:'/show_account'][:initial_date], final_date: params[:'/show_account'][:final_date], format: :csv), class: "btn button-new-transaction" %>
      </div>
    <%end%>
  </div>

  <hr>

  <div class='row'>
    <%= form_for show_account_path, method: :get do |form| %>
      <div class='col-6'>
        <%= form.label :data_inicial%>
        <%= form.date_field :initial_date %>
        <%= form.label :data_final%>
        <%= form.date_field :final_date %>
        <%= form.submit :Pesquisar, class: "btn button-new-transaction"%>
      </div>
    <% end %>
  </div>

  <div>
    <table class="table table-borderless mt-4">
      <thead>
        <tr>
          <th scope="col">Tipo de transação</th>
          <th scope="col">Valor</th>
          <th scope="col">Taxa</th>
          <th scope="col">Destinatário</th>
          <th scope="col">Data</th>
        </tr>
      </thead>
      <tbody>
        <% @transactions&.each do |transaction| %>
          <tr>
            <td><%=transaction.transaction_type %></td>
            <td><%=number_to_currency(transaction.amount, unit: 'R$', separator: ',')%></td>
            <td><%=number_to_currency(transaction.fee, unit: 'R$', separator: ',')%></td>
            <td><%=transaction.account_receiver.user.full_name %></td>
            <td><%=DateTime.parse(transaction.created_at.to_s).strftime("%d/%m/%Y") %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>